#!/bin/bash
  
DIR=$( cd "$( dirname "$0" )" && pwd )
cd $DIR/..

(
  flock -x -w 100 201 && (
    date +"%Y-%m-%d %H:%M:%S"

    mongrel_rails cluster::stop


    mkdir -p tmp/pids
    rm -rf tmp/pids/*

    sleep 5

    mongrel_rails cluster::start
  )
) 201>tmp/restart.lock
